apiVersion: apps/v1
kind: Deployment
metadata:
  name: namee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namee
  template:
    metadata:
      labels:
        app: namee
    spec:
      containers:
      - image: okteto.dev/namee:latest
        name: namee
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "1631849d-925a-4c8c-8d64-3207707b1107"
        - name: Vless_Path
          value: "/v133bb5"
        - name: Vmess_UUID
          value: "1631849d-925a-4c8c-8d64-3207707b1107"
        - name: Vmess_Path
          value: "/vm66bbn"
        - name: Share_Path
          value: "/v2link"
